-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgwYdmQNJgakZE0gYb
Pf+JjOgeuHfgJg9cubLD4uxEGIOgCgYIKoZIzj0DAQehRANCAATCzza/qYggxArG
0wUWVcuxRETkhsC4hEmdgX+Jaj/LncHIZCrlwGUft3stm7W/tqmateiZvEnh8j6d
WmeqHZ7m
-----END PRIVATE KEY-----